# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[files]
extend-exclude = ["third_party"]
ignore-vcs = true

[default.extend-words]
# LOD refers to level of details in graphics.
lod = "lod"

[default.extend-identifiers]
# Don't correct the spelling existing in the Vulkan upstream.
LAYER_NEGOTIATE_UNINTIALIZED = "LAYER_NEGOTIATE_UNINTIALIZED"
