# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[config]
default_to_workspace = false
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[tasks.coverage]
command = "cargo"
args = ["llvm-cov", "nextest", "--all-features", "--all-targets", "${@}"]
install_crate_args = ["--locked"]

[tasks.codegen-check]
# TODO: Detect if LLVM is correctly installed. If not, guide the user to install.
description = "Check if codegen will modify files."
command = "cargo"
category = "Development"
args = [
    "run",
    "--all-features",
    "--release",
    "-p",
    "vulkan-layer-scripts",
    "--bin",
    "codegen",
    "--",
    "--check",
]

[tasks.ci]
command = "cargo"
args = ["run", "-p", "vulkan-layer-scripts", "--bin", "ci", "--", "${@}"]

[tasks.codegen]
command = "cargo"
args = ["run", "-p", "vulkan-layer-scripts", "--bin", "codegen"]

[tasks.license]
description = "Add license to source files."
# TODO: make this also work on Windows: detect go binary install folder via go env GOPATH, and also
# install addlicense if missing.
command = "${HOME}/go/bin/addlicense"
# TODO: test whether the --check argument exists, and add -check accordingly instead of arguments
# passthrough.
args = ["-ignore", "third_party/**", "-ignore", "target/**", "${@}", "."]
