[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.65.1"
env_logger = "0.10.0"
log = "0.4.17"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
