# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# For safety reasons, we have to pin a third-party github action to a specific commit hash.
on:
  pull_request:
    branches: ["main"]
  workflow_call: {}
name: presubmit
jobs:
  buildtest:
    name: Rust build and test
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Linux dependency
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
        if: runner.os == 'Linux'
      - name: Setup LLVM install patrh
        id: setup-llvm-install-path
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "LLVM_INSTALL_PATH=`realpath $GITHUB_WORKSPACE/../LLVM`" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "LLVM_INSTALL_PATH=C:/Program Files/LLVM" >> $GITHUB_OUTPUT
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-llvm-install-path.outputs.LLVM_INSTALL_PATH }}
          key: ${{ format('llvm-16.0.0-{0}', runner.os) }}
      - name: Install LLVM and Clang
        # KyleMayes/install-llvm-action@v2.0.4
        uses: KyleMayes/install-llvm-action@10c8957324ef77f0712d883b9ed08adb6da4a192
        with:
          version: "16.0.0"
          directory: ${{ steps.setup-llvm-install-path.outputs.LLVM_INSTALL_PATH }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: runner.os == 'Windows'
      - name: Set up stable Rust toolchain
        # dtolnay/rust-toolchain@stable
        uses: dtolnay/rust-toolchain@4f366e621dc8fa63f557ca04b8f4361824a35a45
        with:
          components: clippy, llvm-tools-preview
      - name: Set up nightly Rust toolchain
        # dtolnay/rust-toolchain@nightly
        uses: dtolnay/rust-toolchain@f2f3c4b315c5bb8415dbb043af44ec90f68ae503
        with:
          components: rustfmt
      - run: rustup default stable
      - name: Set up Rust dependency cache
        # Swatinem/rust-cache@2.7.8
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          key: ${{ runner.os }}
          cache-all-crates: true
      - name: Install cargo nextest
        run: cargo install cargo-nextest --locked
      - name: Install cargo-make
        run: cargo install --no-default-features --locked cargo-make
      - name: Install cargo llvm cov
        run: cargo install cargo-llvm-cov --locked
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13t"
          cache: "pipenv"
      - name: Install pipenv
        run: python -m pip install pipenv==2025.0.2
      - name: Install python dependencies
        run: pipenv install --ignore-pipfile
      - name: Install addlicense
        run: go install github.com/google/addlicense@master
      - run: cargo make ci-presubmit
      - name: Checkout base coverage
        uses: actions/checkout@v4
        with:
          ref: static_resource
          sparse-checkout: |
            ${{ format('coverage-{0}/lcov.info', runner.os) }}
          sparse-checkout-cone-mode: false
          path: target/base-coverage
      - name: Report coverage
        # 06393993/lcov-reporter-action@master
        # TODO: once the upstream accept the PR, change back to romeovs/lcov-reporter-action@master
        uses: 06393993/lcov-reporter-action@24d48ff28930b87e67d0df34283153b04a76f166
        with:
          lcov-file: target/lcov.info
          lcov-base: ${{ format('target/base-coverage/coverage-{0}/lcov.info', runner.os) }}
          filter-changed-files: true
          title: ${{ format('Test coverage for {0}', runner.os) }}
          post-to: job-summary
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ format('coverage-{0}', runner.os) }}
          # lcov.info is needed for the next commit and PR to diff the coverage report of the base
          # HTML results are needed for human to check the coverage report
          # The coverage badge is used in the README.md.
          path: |
            target/lcov.info
            target/llvm-cov
            target/coverage_badge.json
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ format('doc-{0}', runner.os) }}
          path: target/doc
